name: CI - Pre Build Test

on:
  pull_request:
    branches: [ main ]  # PR이 main, develop 브랜치에 올라왔을 때 실행

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v4

      # 2. pnpm 설치
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # 3. Node 버전 셋업
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'  # pnpm 의존성 캐싱 (node_modules 캐시 최적화)

      # 5. 의존성 설치
      - name: Install dependencies
        run: pnpm install

      # 6. 빌드 
      - name: Build
        run: pnpm run build
